# Generated by Django 5.2 on 2025-05-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
